### ISSUE TITLE
Docstring

### ISSUE THREAD

**Issue by maplepy** [adhesivecheese/pmtw#2]
Hello,

You might have seen the pull request that I actually canceled because of new issues but the docstring is not formatted correctly in your code, please fix that so we can use the intellisense in our own code. I wanted to fix it for you but somehow I had a bunch of errors about `Inconsistent use of tabs and spaces in indentation` so I kind of gave up, I don't know what's causing it and everytime I use tab to indent a code block, I get this error

For example

```python
	"""
	Get Removal Reasons information as a list. Use
	get_removalReasons(local="False") to fetch from Reddit before returning.
	"""
	@localdata
	def get_removalReasons(self):
```

should be like this:
```python
	@localdata
	def get_removalReasons(self):
		"""
		Get Removal Reasons information as a list. Use
		get_removalReasons(local="False") to fetch from Reddit before returning.
		"""
```

Thank you

**Comment by maplepy** [comment]
Seems like you gave up on the project a long time ago :/

**Comment by adhesivecheese** [comment]
Very much haven't given up; just been very busy with other projects. I have a ground up rewrite that should actually be out in a few days that'll fix this amongst other things.

**Comment by adhesivecheese** [comment]
1.0.0 has been released which *should* give you proper docstrings. Please let me know if you have issues!
