### ISSUE TITLE
un.add_note(n) should be notes.add_note(n) in the Adding a note example

### ISSUE THREAD

**Issue by woutware** [adhesivecheese/pmtw#4]
un.add_note(n) should be notes.add_note(n) in the Adding a note example.

Other than that this module works great.

**Comment by adhesivecheese** [comment]
Thanks! I'm just finishing up a major rewrite which will have much more thorough documentation.

**Comment by adhesivecheese** [comment]
I've just pushed 1.0.0 with completely different documentation, so closing this issue.
